name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # 每次推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境中运行

    steps:
      # Step 1: Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 设置 Docker Buildx（用于构建 Docker 镜像）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录到阿里云 Docker 镜像仓库
    - name: Log in to Alibaba Cloud Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.ALIYUN_ACCESS_KEY_ID}}
        password: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        registry: ${{ secrets.ALIYUN_REGISTRY }}

      # Step 4: 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ALIYUN_REGISTRY }}/myapiapp:latest .

      # Step 5: 推送 Docker 镜像到阿里云容器镜像服务
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ALIYUN_REGISTRY }}/myapiapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 确保部署是在构建之后执行

    steps:
      # Step 6: Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 7: 部署到阿里云服务器
      - name: Deploy Docker image to Alibaba Cloud server
        uses: appleboy/ssh-action@v0.1.8  # 使用 SSH Action 来连接服务器并部署
        with:
          host: ${{ secrets.SERVER_IP }}  # 服务器 IP 地址
          username: ${{ secrets.SSH_USERNAME }}  # SSH 登录用户名
          password: ${{ secrets.SSH_PASSWORD }}  # 如果使用密码进行登录
          # key: ${{ secrets.SSH_PRIVATE_KEY }}  # 如果使用私钥登录，可以解开这一行并注释掉密码
          port: 22
          script: |
            # 登录到阿里云容器镜像
            echo ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} | docker login --username=${{ secrets.ALIYUN_ACCESS_KEY_ID }} --password-stdin ${{ secrets.ALIYUN_REGISTRY }}

            # 拉取最新镜像
            docker pull ${{ secrets.ALIYUN_REGISTRY }}/myapiapp:latest

            # 停止并移除旧容器（如果存在）
            docker stop myapiapp-container || true
            docker rm myapiapp-container || true

            # 启动新的容器
            docker run -d --name myapiapp-container -p 44375:44375 ${{ secrets.ALIYUN_REGISTRY }}/myapiapp:latest
